[package]
name = "paypaul"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
bdk = { version = "0.26.0", features = ["sqlite"] }
dotenv = "0.15.0"
